name: deploy

on: 
  push:
    branches:
      - main
jobs:
  push-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node version
        uses: actions/setup-node@main
        with:
          node-version: 14
          
      - name: Npm install
        run: npm install

      - name: Build dist
        run: npm run build
      
